import React, { useState } from "react";
import TestMetricsMultiselect from "../OnWholeApp/helperFunctions";

/*

Checks/validation can be included in the componenet later as these not invlove changing something out of this file...
this can be done by simply implementing the validation schema and Resolvers from react-hook-form to link the
checks mentioned in the schema

schema of this component (model_info obj generated by this component):

==================================================
sample model_info object:

  "model_info": {
    "C": 0.5,
    "lr": 0.01,
    "n_iters": 100,
    "weights_shape": "(5, 10)",
    "binary_classification": true,
    "test_metrics": ["accuracy", "f1_score"]
  }

==================================================

*/

const CustomSVM = ({ control, register }) => {
  const defaultValues = {
    C: 0.5,
    lr: 0.01,
    n_iters: 100,
    weights_shape: "(5, 10)",
    is_binary: "false",
  };

  // Start of model_info component
  return (
    <div>
      <p>
        Note: Weight shape is optional but required when all clients don't have
        the same number of classes
      </p>

      {/* C: Regularization parameter */}
      <div className="input-group mb-3">
        <span className="input-group-text">C/Regularization parameter</span>
        <input
          type="number"
          className="form-control"
          placeholder="e.g. 0.5"
          defaultValue={defaultValues.C}
          {...register("model_info.C")}
        />
      </div>

      {/* Learning rate */}
      <div className="input-group mb-3">
        <span className="input-group-text">Learning rate</span>
        <input
          type="number"
          className="form-control"
          placeholder="e.g. 0.01"
          defaultValue={defaultValues.lr}
          {...register("model_info.lr")}
        />
      </div>

      {/* Number of iterations */}
      <div className="input-group mb-3">
        <span className="input-group-text">#iter</span>
        <input
          type="number"
          className="form-control"
          placeholder="number of iterations in 1 epoch e.g. 100"
          defaultValue={defaultValues.n_iters}
          {...register("model_info.n_iters")}
        />
      </div>

      {/* Weight shape */}
      <div className="input-group mb-3">
        <span className="input-group-text">Weight shape</span>
        <input
          type="text"
          className="form-control"
          placeholder="e.g. (5, 10) for 5 classes and 10 features per class"
          defaultValue={defaultValues.weights_shape}
          {...register("model_info.weights_shape")}
        />
      </div>

      {/* Binary classification */}
      <div className="input-group">
        <span className="input-group-text">Binary Classification</span>
        <div className="form-check form-check-inline mx-auto">
          <input
            className="form-check-input"
            type="radio"
            name="inlineRadioOptions"
            id="inlineRadio1"
            value="true"
            defaultChecked={defaultValues.is_binary === "true"}
            {...register("model_info.is_binary")}
          />
          <label className="form-check-label" htmlFor="inlineRadio1">
            Yes
          </label>
        </div>
        <div className="form-check form-check-inline mx-auto">
          <input
            className="form-check-input"
            type="radio"
            name="inlineRadioOptions"
            id="inlineRadio2"
            value="false"
            defaultChecked={defaultValues.is_binary === "false"}
            {...register("model_info.is_binary")}
          />
          <label className="form-check-label" htmlFor="inlineRadio2">
            No
          </label>
        </div>
      </div>

      {/* Select test metrics */}
      <TestMetricsMultiselect register={register} />
    </div>
  );
};

export default CustomSVM;
