import React from "react";
import SelectTestMetrics from "../RequestComponents/SelectTestMetrics";
import { useFormContext } from "react-hook-form";
import {
  AdjustmentsHorizontalIcon,
  HashtagIcon,
} from "@heroicons/react/24/outline";

/*
Checks/validation can be included in the component later as these do not involve changing something out of this file...
This can be done by simply implementing the validation schema and Resolvers from react-hook-form to link the
checks mentioned in the schema

schema of this component (model_info obj generated by this component):

==================================================
sample model_info object:

  "model_info": {
    "lr": 0.01,
    "n_iters": 100
  }

==================================================
*/

const LinearRegression = () => {
  const { register } = useFormContext();
  const defaultValues = {
    lr: 0.01,
    n_iters: 1,
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <p className="text-lg font-semibold mb-4">
        Configure the Linear Regression Model Parameters:
      </p>

      {/* Learning Rate */}
      <div className="mb-4">
        <label className="flex items-center text-gray-700 font-medium mb-1">
          <AdjustmentsHorizontalIcon className="h-5 w-5 mr-2 text-blue-500" />
          Learning Rate
        </label>
        <input
          type="number"
          step="0.01"
          placeholder="e.g. 0.01"
          defaultValue={defaultValues.lr}
          {...register("model_info.lr")}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none"
        />
      </div>

      {/* Number of Iterations */}
      <div className="mb-4">
        <label className="flex items-center text-gray-700 font-medium mb-1">
          <HashtagIcon className="h-5 w-5 mr-2 text-blue-500" />
          Number of Iterations
        </label>
        <input
          type="number"
          placeholder="e.g. 1"
          defaultValue={defaultValues.n_iters}
          {...register("model_info.n_iters")}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none"
        />
      </div>

      {/* Select test metrics */}
      <SelectTestMetrics register={register} />
    </div>
  );
};

export default LinearRegression;
