"""Initial migration

Revision ID: 1999d4d5bddc
Revises: 
Create Date: 2025-04-04 13:31:34.159230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1999d4d5bddc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('datastats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_datasets_dataset_id'), 'datasets', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_datasets_filename'), 'datasets', ['filename'], unique=True)
    op.create_table('raw_datasets',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('datastats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_raw_datasets_dataset_id'), 'raw_datasets', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_raw_datasets_filename'), 'raw_datasets', ['filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_datasets_filename'), table_name='raw_datasets')
    op.drop_index(op.f('ix_raw_datasets_dataset_id'), table_name='raw_datasets')
    op.drop_table('raw_datasets')
    op.drop_index(op.f('ix_datasets_filename'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_dataset_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
