"""Add CurrentTrainings table

Revision ID: 3c09b0d878bf
Revises: fa15af53f071
Create Date: 2025-04-10 23:15:13.726841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c09b0d878bf'
down_revision: Union[str, None] = 'fa15af53f071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_trainings',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('training_details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('training_id')
    )
    op.create_index(op.f('ix_current_trainings_session_id'), 'current_trainings', ['session_id'], unique=False)
    op.create_index(op.f('ix_current_trainings_training_id'), 'current_trainings', ['training_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_trainings_training_id'), table_name='current_trainings')
    op.drop_index(op.f('ix_current_trainings_session_id'), table_name='current_trainings')
    op.drop_table('current_trainings')
    # ### end Alembic commands ###
